### ISSUE TITLE
How can I create the configuration for the AWS Batch environment?

### ISSUE THREAD

**Issue by zhangzhen** [pepkit/pepenv#10]
Divvy is a wonderful tool. But I cannot find any example of the configuration for the cloud environment, e.g. the AWS Batvh environment. Can you please give me some hints about how to do that or what code I should write to implement that.

Cheers,
Zhen Zhang

**Comment by nsheff** [comment]
I believe this is possible, but I haven't done it.

From what I understand about AWS Batch, you would need to create a template "Job definition" file, that you would use as a divvy template, so you would add a new compute package to your divvy config file, say `aws_batch`. You'd point this `template` to an AWS job definition file.  The `submission_command` would be `submit-job` using the AWS job definition, so something like:

```
compute_packages:
  aws_batch:
    submission_template: job_definition_template.txt
    submission_command: "submit-job --job-definition "
```

I think this would work, but I haven't tried it. Let me know if you need more pointers.
